### ISSUE TITLE
Please use only one repo

### ISSUE THREAD

**Issue by pcav** [nextgis/QTiles#104]
The new version of the plugin: http://plugins.qgis.org/plugins/QTiles/ uses a different repo. It would be much preferable if it could be added to the original one, with appropriate metadata, as this would simplify the management of the plugin and reduce the uncertainty for the users. 
Thanks.

**Comment by simgislab** [comment]
we're not related to this, ours is http://plugins.qgis.org/plugins/qtiles/

https://github.com/nextgis/QTiles/issues/94#issuecomment-456916246

**Comment by pcav** [comment]
Sorry for the noise, the new version authors wrongly added metadata.

**Comment by nurenda** [comment]
Sorry for the inconvenience. Should I push a new version correcting only the metadata?

**Comment by pcav** [comment]
A new version in the same repo would be much preferable.
@simgislab , any objections?

**Comment by saberraz** [comment]
@nurenda the xyz plugin is now a processing in QGIS core (master) and backported to QGIS 3.x using this:
https://github.com/lutraconsulting/qgis-xyz-tiles
and:
http://plugins.qgis.org/plugins/tiles_xyz/

**Comment by nurenda** [comment]
How can I test this processing?

Thanks in advance

**Comment by saberraz** [comment]
QGIS 3.4:
Go to Plugins and search for Tiles XYZ. Install the plugin. Open Processing Toolbox and search for XYZ tile and you should be able to run it from there.

**Comment by simgislab** [comment]
We're already working on our version of QTiles for QGIS3.

**Comment by nurenda** [comment]
> QGIS 3.4:
> Go to Plugins and search for Tiles XYZ. Install the plugin. Open Processing Toolbox and search for XYZ tile and you should be able to run it from there.

OK!

Got it working. It does not appear in the plugins list on QGis 3.6, only 3.4.

**Comment by nurenda** [comment]
> We're already working on our version of QTiles for QGIS3.

Maybe we could merge your version an mine. The problem is, I can't push it to the GitHub repository. How can we work that?

**Comment by nurenda** [comment]
> QGIS 3.4:

I see en the **metadata** file of your project that the _qgisMaximumVersion=3.6._

Apparently, that prevents to see the plugin from QGis 3.6.**2**. Maybe you could update, or simply comment, that variable...

**Comment by saberraz** [comment]
@nurenda please use  https://github.com/lutraconsulting/qgis-xyz-tiles for reporting issues regarding to our plugin.

A new version has just been released.

**Comment by simgislab** [comment]
please stop using these threads to discuss unrelated software
