### ISSUE TITLE
QTiles module does not start 

### ISSUE THREAD

**Issue by Romchik93** [nextgis/QTiles#110]
After starting processing the module begins scrolling the progress bar endlessly, but never starts processing.

Link to file https://cloud.mail.ru/stock/13au1Ng1ZjzmAJjda88im3h8
![image](https://user-images.githubusercontent.com/39699899/91280295-385a4100-e78f-11ea-8ee3-5eacaf66518e.png)

**Comment by Romchik93** [comment]
https://support.nextgis.com/#ticket/zoom/407

**Comment by alisovenko** [comment]
Fixed in 53302a517ecd94079d644fac59d2f35be7a9b3a1
