### ISSUE TITLE
Python error on "browse" buttons (QGIS 3)

### ISSUE THREAD

**Issue by eduard-kazakov** [nextgis/QTiles#112]
When pushing button "..." (browse) in any mode, python error occurs:

NameError: name 'QFileDialog' is not defined 
Traceback (most recent call last):
  File "C:/Users/ekazakov/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtiles\qtilesdialog.py", line 400, in __select_output
    outPath, outFilter = QFileDialog.getSaveFileNameAndFilter(self, self.tr('Save to file'), file_directory, ';;'.join(iter(list(self.FORMATS.keys()))), list(self.FORMATS.keys())[list(self.FORMATS.values()).index('.zip')])
NameError: name 'QFileDialog' is not defined

QGIS 3.18, QTiles 1.6

**Comment by UserWithoutAuth** [comment]
Same over here, I've ended up installing QGIS 2 and manually installing QTiles version 1.5.2.1

**Comment by 514ckw4r3** [comment]
Fixed in 1.7.0
