### ISSUE TITLE
Python error instead of message, when "Extent from layer" combobox is empty

### ISSUE THREAD

**Issue by eduard-kazakov** [nextgis/QTiles#113]
Must be:
1. Message, that no layer selected
2. button to reload list of layers in combobox (without reopening plugin)

Python error:

AttributeError: 'NoneType' object has no attribute 'extent' 
Traceback (most recent call last):
  File "C:/Users/ekazakov/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtiles\qtilesdialog.py", line 242, in accept
    extent = canvas.mapSettings().layerExtentToOutputExtent(layer, layer.extent())
AttributeError: 'NoneType' object has no attribute 'extent'

QGIS 3.18, QTiles 1.6

**Comment by 514ckw4r3** [comment]
Error fixed in 1.7.0.
Created a separate issue for the reload-button https://github.com/nextgis/QTiles/issues/116
