### ISSUE TITLE
Something gone wrong with QGIS 2.4 (MTR-related?)

### ISSUE THREAD

**Issue by nirvn** [nextgis/QTiles#22]
Under QGIS 2.4, QTiles seems to be unable to render layers with proper scale for millimeter values et cie.

It must have something to do with the amazing MRT work done for QGIS 2.4, and how it drastically changed the way scale and dpi values are handled.

What I see broken:
- Lines as width as 10mm will draw as a thin 1 pixel width line
- Symbology such as shapeburst fails, it seems unable to properly register units (such as shapeburst distance from border). I noticed both shapeburst and line fill pattern are broken

Is this something the author(s) is/are aware of?

**Comment by simgislab** [comment]
can you please update to a newer QGIS and try again?

On my 2.8 it works well (this is one of the tiles), line width seems to be taken into account while rendering:

![](http://m-d.me/img/ss/20150903-qu9-224kb.jpg)

**Comment by alisovenko** [comment]
Can't reproduced for qgis 2.8.3
