### ISSUE TITLE
Rendering vector shapes with label text that spans multiple tiles

### ISSUE THREAD

**Issue by w879ms2** [nextgis/QTiles#24]
I have an issue when I create tiles from vector shapes with label text that spans multiple tiles. The text appears ok in the tile where the text is anchored but if the text spans another tile then the text does not appear in the adjacent tile. It therefore looks like the text has been cropped. Any help with this would be very much appreciated. The image below show 2 adjacent tiles...
![fullsizerender](https://cloud.githubusercontent.com/assets/10091396/5322166/dc5f9ba6-7cba-11e4-8887-6e4e3d1d1703.jpg)

**Comment by 3nids** [comment]
same issue as #1
