### ISSUE TITLE
Error loading plugin in Win7 QGIS 2.6.1

### ISSUE THREAD

**Issue by kgs2x** [nextgis/QTiles#31]
Trying to install the plugin in Windows QGIS 2.6.1 results in the error message: "The plugin is broken. Python said: No module named ui_qtilesdialogbase".

**Comment by simgislab** [comment]
Works fine here on Win7, did you trying installing other plugins? Do they work?

**Comment by fegyi001** [comment]
The module is broken. You can fix it with the following steps:
- rename aboutdialogbase.ui to ui_aboutdialogbase.ui
- rename qtilesdialogbase.ui to ui_qtilesdialogbase.ui
- rename resources.qrc to resources_rc.qrc
- make sure you can run pyrcc4 and pyuic4 from command line (add OSGeo4W\bin folder to PATH environmental variable)
- run the following commands from the plugin root folder:
    - pyuic4 -o ui\ui_qtilesdialogbase.py ui\ui_qtilesdialogbase.ui
    - pyuic4 -o ui\ui_aboutdialogbase.py ui\ui_aboutdialogbase.ui
    - pyrcc4 -o resources_rc.py resources_rc.qrc
- restart QGIS, everything should be fine now.

**Comment by simgislab** [comment]
The recipe above is for developers, not users, it doesn't fix the plugin in the repository.

There was an error in plugin packaging, should be fixed now. Please update plugin from the repo.

Reopen if necessary.
