### ISSUE TITLE
Error: No module named ui_qtilesdialogbase on Ubuntu 14.04 QGIS 2.6

### ISSUE THREAD

**Issue by sharthZ** [nextgis/QTiles#33]
When i try install QTiles plugin i get error "No module named ui_qtilesdialogbase" :(

**Comment by simgislab** [comment]
duplicates #31, please reinstall from the repo, it should fix the problem

**Comment by simgislab** [comment]
strange, but the archive was again broken, had to repackage, please try again and let me know if it works now (you might need to remove the old not-working one first)

**Comment by sharthZ** [comment]
Now it works, thank u)

2015-02-12 22:11 GMT+03:00 Maxim Dubinin <notifications@github.com>:
