### ISSUE TITLE
Qtiles not processing

### ISSUE THREAD

**Issue by charlie1564** [nextgis/QTiles#34]
Hi,

I'm trying to compile some maps with Qtiles after razterisation in Qgis.
When I click OK to start the processing the progress bar gets a blue section moving from rigth to left but no % and it stays like that (1 day) until I cancel the processing.
I'm using GIS 2.6.1 with win8 and I tried the last Qtiles update and also older ones.
Does anyone knows what I am doing wrong
Many thanks,
Charlies

**Comment by simgislab** [comment]
Hi, what other QTiles settings do you use?

**Comment by simgislab** [comment]
please reopen if this is still a problem and you can provide needed feedback
