### ISSUE TITLE
NextGIS Mobile doesn't show QTiles' tiles

### ISSUE THREAD

**Issue by sant9ga** [nextgis/QTiles#37]
Hello!
QGis 2.8.1, QTiles 1.4.5. I'm trying to create tiles to use wtih nextGisMobile. What I do and what I found strange:
1) Tried to replace "~osmdroid\tiles\Mapnik" folder with standard osm tiles to my own "Mapnik" with QTiles' outputs in different scales (17,18 for example). 
Strange: numbers of folders of osm's tiles (before their deleting) and qtiles' outpus are the same or very close (~Mapnik\18\153073 for example), but their contents have different names (~Mapnik\18\153088\76340.png.tile with OSM and ~Mapnik\18\153073\185789.png with QTiles). Also QTiles' have THE SAME names of tiles in every folder (the same names in "~18\153073\*" and "~18\153074\*" and so forth). Does the projection matters?
2) QTiles' outputs don't have *.png.TILE extension. Tried to change all the .png into .png.tile, but it didn't change anything. Should I add .tile to the files?
3) Which checkbox should be turned on to do the proper tiles for NextGIS Mobile? This is the way I did it:
![img](https://cloud.githubusercontent.com/assets/11545131/6719260/6a6897b2-cdca-11e4-92b4-3650a5e247f8.png)

4) Tried to create zip with QTiles, placed it everywhere: in osmdroid, in osmdroid\tiles and so forth - nothing chenges.
I tried with and tried without "Use TMS...". The result: if the internet on cellphone is off - there is no map. If it's on - osm tiles are downloading, no matter how many own-made tiles where there.

What do I do wrong?
Thank you!

**Comment by BishopGIS** [comment]
1) You don't have to replace program tile cache with your own. Use zip instead.
2) This option is not for NextGIS Mobile. It use for generate tiles for server and access them fron OL or Lefleat
3) You have to check "File" and select zip format
4) You have to place the zip file to your /sdcard/osmdroid. Also, if you have tiles from OSM in device cache they will override you cache data. So you need to cleare the cache - delete the  osmdroid\tiles folder using some explorer - i.e. EZ Explorer (https://play.google.com/store/apps/details?id=com.estrongs.android.pop)

**Comment by sant9ga** [comment]
Thank you for the quick respond!

I've tried everything like you said, but nothing works:(
Here the tiles zip file: https://www.dropbox.com/s/67ullbjgol0hwdv/spb_technolozhka.zip?dl=0
there is 16-zoom test-map, 2 folders in there. As I said all the files in that 2 folders have the same names: 19062.png and 19063.png in ~16\38286\ and same names in 16\38287\ - is it right?
I placed this .zip in osmdroid, "tiles" folder was deleted. 
![pic1](https://cloud.githubusercontent.com/assets/11545131/6726457/8f68eebe-ce28-11e4-9f59-9c5caae31fd3.JPG)
Internet on device for nextgis is blocked by Droidwall. I open nextgis and see nothing in all scales.

Please help to resolve this problem! Very need my map before saturday.

Regards.

**Comment by BishopGIS** [comment]
The provided zip is not valid. The root folder has name "spb_tech", but should have - "Mapnik". The tiles are ok (and yes, they can have the same names in different folders: tiles in one row have same names and folders in one column).
![screen2](https://cloud.githubusercontent.com/assets/1708122/6729547/f5b772ca-ce65-11e4-80d3-62bc51ca0ba3.png)

**Comment by sant9ga** [comment]
Спасибо огромное, комрад!=) Все получилось!
Однозначно 5 звезд за плагин!

P.S. а с папками вместо архивов приложение уже не работает? Или ускорение незначительным получается?

**Comment by BishopGIS** [comment]
Во второй версии будет (http://nextgis.ru/d-day/presentations/6-baryshnikov-mobile.pdf). Надеюсь скоро релиз. 
Как минимум требование по наименованию папки Mapnik снято. Вторая версия NextGIS Mobile будет кушать любое название папки в корне и даже если в корне идут сразу папки уровня Z.

**Comment by simgislab** [comment]
@BishopGIS closing?

**Comment by BishopGIS** [comment]
Ага
