### ISSUE TITLE
Can't select output file containing cyrillic characters

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/QTiles#38]
If cyrillic characters present in full path name, error appears:

>Ошибка при выполнении сценария Python:
>
>
>Traceback (most recent call last):
>  File "C:/NEXTGI~1/apps/qgis/./python/plugins\qtiles\qtilesdialog.py", line 206, in __selectOutput
>    print outPath
>UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-43: ordinal not in range(128)
>
>
>Версия Python:
>2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
>
>
>Версия:
>2.8.1-Wien Wien, ddccf8e
>
>Путь поиска Python: ['C:/NEXTGI~1/apps/qgis/./python/plugins\\processing', 'C:/NEXTGI~1/apps/qgis/./python', u'C:\\Documents and Settings\\Silhouette\\NextGIS QGIS/python', u'C:\\Documents and Settings\\Silhouette\\NextGIS QGIS/python/plugins', 'C:/NEXTGI~1/apps/qgis/./python/plugins', 'C:\\NEXTGI~1\\bin\\python27.zip', 'C:\\NEXTGI~1\\apps\\Python27\\DLLs', 'C:\\NEXTGI~1\\apps\\Python27\\lib', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\plat-win', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\NEXTGI~1\\bin', 'C:\\NEXTGI~1\\apps\\Python27', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\site-packages', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\NEXTGI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:\\Documents and Settings\\Silhouette\\NextGIS QGIS/python', 'C:\\NEXTGI~1\\apps\\qgis\\python\\plugins\\fTools\\tools']

**Comment by simgislab** [comment]
Tried to generate to directory: C:\temp\qtiles\дир

In my case - no error, but OK button grays out and stays like that forever.

So something is definitely wrong with cyrrilic dirs.
