### ISSUE TITLE
Duplicate tiling when background tile transparency set to 0

### ISSUE THREAD

**Issue by nlyman** [nextgis/QTiles#39]
Duplicate and erroneous tiles are being created when trying to export MBtiles with background tiles set to be transparent.  I am trying to export a single band raster from zoom level 6 to 10, and this is the current result (attached image).

![image](https://cloud.githubusercontent.com/assets/11197050/7242338/73c52d5a-e776-11e4-9f50-e6769a108877.png)

**Comment by perrygeo** [comment]
I can confirm this, using a vector layer as well. 

Example tile with background transparency set to `255` (default; not transparent)

![bg255](https://cloud.githubusercontent.com/assets/1151287/7254567/cbc64b42-e7f8-11e4-941b-89eb1ce45592.png)

And an example with the same data, same tile, setting background transparency to `0`:

![bg0](https://cloud.githubusercontent.com/assets/1151287/7254582/e8dbe23c-e7f8-11e4-95c0-06684df51078.png)

This is a critical bug for most tile production use cases - can anyone advise a workaround?

**Comment by tmcadam** [comment]
I can confirm I am having the the same issue as well,
![161033](https://cloud.githubusercontent.com/assets/1412437/8368115/9485b828-1be9-11e5-9857-de5d2c79016e.png)
![161033](https://cloud.githubusercontent.com/assets/1412437/8368121/a1703fd6-1be9-11e5-894c-5b8acdcb7769.png)

**Comment by pchapuis** [comment]
To be more specific, it seems that this duplication behaviour always happens. It's just you don't see it when the transparency is set with a full opacity.
![image](https://cloud.githubusercontent.com/assets/13674352/9106536/45902f02-3c21-11e5-9b09-097fd4189e45.png)

**Comment by simgislab** [comment]
confirm that, easily replicated by setting Background transparency to 0

EPSG: 4326, on-the-fly is on

Original:

![](http://m-d.me/img/ss/20150903-e82-76kb.jpg)

Rendered:
![](http://m-d.me/img/ss/20150903-rq6-296kb.jpg)

**Comment by perrygeo** [comment]
@alisovenko can you reference the commit(s) that fixed this? Thanks

**Comment by simgislab** [comment]
fix code: https://github.com/nextgis/QTiles/compare/6f16f493ed...1c38035882
