### ISSUE TITLE
Wrong CRS in Lefleat-based viewer

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/QTiles#40]
Можно создать автоматически HTML-файл с просмотрщиком. При этом создается базовый слой из OSM онлайновый, и второй слой со скачанными тайлами. Поэтому при просмотре есть возможность сравнить чего имеем онлайн, и чего получается в скачанном слое. Так вот видно, что картинка скачанного слоя получается несколько смещенной относительно базового из интернета.

У кого ни будь воспроизводится?

**Comment by alisovenko** [comment]
У меня не воспроизвелась

**Comment by BishopGIS** [comment]
А ты тайлы из ОСМ нарезал? Т.е. кейс был, что человек подключил ОСМ через QMS нарезал в нем тайлы и потом сравнивает их с нимиже онлайн.

**Comment by alisovenko** [comment]
Да, так воспроизвелась ошибка.

Сперва я скачал shp отсюда http://beryllium.gis-lab.info/project/osmshp/ - с ним нормально отработало.

**Comment by alisovenko** [comment]
Если включить автоматическое перепроецирование на EPSG:4326, то эта ошибка не наблюдается.
Может кто-нибудь подтвердить?

**Comment by simgislab** [comment]
подтверждаю

1. Взял проект
2. Подключил через QMS OSM Mapnik
3. Выстапил 3857 и on-the-fly
4. Экспортировал в папку с leaflet-viewer с 10 по 11 уровни
5. Включаю-выключаю слой Mapnik, вижу сильное смещение

**Comment by alisovenko** [comment]
Сделано
