### ISSUE TITLE
Maximum zoom doesn't go higher than 18

### ISSUE THREAD

**Issue by simgislab** [nextgis/QTiles#61]

**Comment by pcav** [comment]
Agreed, going up to 19 would seem appropriate (perhaps with a warning that this may require plenty of disk space and time to process).

**Comment by wesweaver** [comment]
I'd say it may even be beneficial to go higher than 19. For example, I'm using very high resolution (.5 cm GSD) aerial imagery, and it would be great to be able to render close to that level. With UAVs growing in usage, I imagine a lot of people are going to want to render tiles at very high zoom levels.

**Comment by reyemtm** [comment]
Zoom level 20 would be great. Maybe in advanced settings?

**Comment by wesweaver** [comment]
After looking into it a bit, I think up to level 22 would be ideal.

**Comment by colla70** [comment]
I attach a screenshot of cadastral tiles in geopaparazzi at 18 zoom level (more or less 1:5000).
![screenshot_20160719-115731](https://cloud.githubusercontent.com/assets/13482593/16947085/42619476-4dad-11e6-9421-d70a91e22314.jpg)
If I could I would be rather happy if this was my min zoom level...so I agree with max zoom level 22 with warning as pcav said.

**Comment by reyemtm** [comment]
Keep in mind that each zoom level exponentially increases the number of
tiles. The difference between zoom 18 and zoom 22 would be HUGE unless you
just want to do a very small area like a few square miles/km. Plus this
option can be changed in the code easily. I think just a bump to 19 for
default highest setting would be good for most use cases.

**Comment by wesweaver** [comment]
Just this morning I processed a bunch of geotiffs to level 24. It is huge, but it's useful in certain areas, especially now that everyone is out collection sub-centimeter GSD imagery with drones.

I don't use QTiles anymore and instead just use GDAL command line (gdal2tiles.py) for this reason. I think for the community that does rely on QTiles it could still be very useful.

**Comment by reyemtm** [comment]
Just curious and not so slightly off topic...are you using multi threads
and/or saving as jpeg? I started using gdal2tiles directly as well for
those two reasons.

**Comment by reyemtm** [comment]
But on topic, if a higher zoom level is allowed, could there be an estimate
file size before executing?

**Comment by robinpaulson** [comment]
Hi, yeah I'd like to see the max zoom increased as well. Is there any particular reason we can't take it beyond 18? I realise it may generate lots and lots of tiles/data, but the user can decide for themselves if that's appropriate or not. Estimates of size and number of tiles would be useful, before pressing "Run".

**Comment by robinpaulson** [comment]
While we're waiting for milestone 1.6, could someone explain which files to edit so I can push zoom to say 22? I know a bit of Python but got variable and only partially useful results when I modified the code..

**Comment by nicpitsch** [comment]
In my experience it's enough to modify the default value of the MAX_ZOOM_LEVEL variable within qtilesdialog.py. After restarting QGIS the max-level is adapted. The plugin directory is available from the Plugins window within QGIS.

**Comment by simgislab** [comment]
no limit now, https://github.com/nextgis/QTiles/commit/7132c4c99818a14cb5cae50dfbebeff44fb6e236
