### ISSUE TITLE
labels are clipped

### ISSUE THREAD

**Issue by geodavid76** [nextgis/QTiles#74]
I have created tiles using this plugin and found that some of the labels we had in the project are cut on the tile edge. Seems that the label is not buffered enough when tiled. I saw this on older posts but seems not to be solved, is this something you are working on?
![label_cut_qtiles](https://cloud.githubusercontent.com/assets/22502728/19522748/94574236-9618-11e6-9a24-ffbec5eeb5b8.jpg)
Thanks!

**Comment by simgislab** [comment]
yes this is duplicate with #1 

I realize this is painful for some, but there is no work currently going on this. We're looking for funding to devote enough time to fix this.
