### ISSUE TITLE
QGIS3 compatibility

### ISSUE THREAD

**Issue by Malauch** [nextgis/QTiles#88]
I just tried QGIS3 and I was surprised that QTiles isn't in plugins repository. Are there any plans for developing QGIS3 version? I'm just an user so I can't edit code to make it works.

**Comment by simgislab** [comment]
No particular plans as of now, consider sponsoring.

**Comment by HerbFargus** [comment]
just as an fyi, this functionality seems to be baked in at 3.8

https://qgis.org/en/site/forusers/visualchangelog38/index.html?highlight=mbtiles#feature-generate-raster-xyz-tiles

**Comment by simgislab** [comment]
QTiles for QGIS 3 is released
