### ISSUE TITLE
crash when file exists

### ISSUE THREAD

**Issue by lukaszkruk** [nextgis/QTiles#91]
When creating a new tileset (zip or mbtiles), the plugin will crash QGIS if the file i'm trying to write already exists.

QGIS 2.18, QTiles 1.5.2.1, Windows 10.

**Comment by simgislab** [comment]
duplicate of #78

**Comment by ukulala** [comment]
after the rendering using QTILE 1.5.2.1 the images tiled resulted to duplicate or cut city names
![mapnik](https://user-images.githubusercontent.com/42261507/43942112-51a27534-9ca9-11e8-8b9c-6a16daa717ea.JPG)
