### ISSUE TITLE
Updates for QGIS 3

### ISSUE THREAD

**Issue by jacksonvoelkel** [nextgis/QTiles#94]
Are there any plans to update this plugin to be compatible with QGIS 3? The current stable version of QTiles does not work in the new release of QGIS.

**Comment by gamayos** [comment]
Same question here. QGIS 3 version would be greatly appreciated!

**Comment by simgislab** [comment]
no particular plans yet, rewrite is a major effort, and we mostly use LTR ourselves

consider sponsoring it

**Comment by jacksonvoelkel** [comment]
What would the rewrite entail?

**Comment by pierrebonbon** [comment]
Same here

**Comment by mkunzBGC** [comment]
Would be great to have this working for QGIS 3!

**Comment by dhildreth** [comment]
👍

**Comment by koenigherford** [comment]
It would be great to have QGIS-3 version of this great plugin !

**Comment by boesiii** [comment]
Same.  Please upgrade for QGIS 3.

**Comment by RockWest** [comment]
I've been looking all over for another way to export my maps into mobile offline databases from QGIS 3.x without success.

I'd be happy to contribute some funds to the rewrite.

**Comment by kannes** [comment]
A experimental version is now available in QGIS 3 thanks to sponsoring by https://gamaya.com/

**Comment by simgislab** [comment]
thanks gamaya for bringing yet another split in the community

**Comment by anakaine** [comment]
There are no links to the QGIS 3 compatible version on either the QGIS
plugins page or the nextgis git repository.

This was closed prematurely if it's not readily available to the community.

**Comment by fqdb** [comment]
http://plugins.qgis.org/plugins/qtiles3/

The maker is not affiliated with nextgis though

**Comment by simgislab** [comment]
sorry it was emotional. It is a very disappointing situation. Instead of contacting us or providing a PR someone is just making a duplicate. We had our plan for upgrading QTiles.

**Comment by kannes** [comment]
Ouch, it is disappointing to hear that this was a "clandestine" port. I assumed they had sponsored *you* to update it. At the very least this should be a PR to this repository so that future work can continue under your oversight.

**Comment by vascotenner** [comment]
@alexbruy Can you please create a PR with your changes on QTiles?

**Comment by gamayos** [comment]
@simgislab the port was sponsored by me and I had absolutely no intent to upset anybody. I worked with @alexbruy on another project and had this ad hoc request for him. I rely on your understanding.

**Comment by simgislab** [comment]
tbh, I don't see how any of this information matter. You introduced a split using very bad open source practice. Please fix it.

**Comment by anakaine** [comment]
@Gamayos For whatever misgivings others have, you have made some big steps
toward fixing what has been untouched for a long time but also something
that the rest of us have been after.

There are a few less than polite people in this thread. Thanks for
committing your resources to this.

**Comment by koenigherford** [comment]
As QGIS 2.x is no longer supported a QGIS 3.x version would be greatly appreciated! We have got several areas in our town where i can only use offline maps because of lack of signal quality using mobile devices. Further we use applications which recommend offnine-tiles as backgrund maps. 
Are there possibilities to support your development ?

**Comment by sfkeller** [comment]
@simgislab Since plugins are GPL it's perfectly OK to me if someone forks the code and publishes it. Having said this, it's really necessarily best OSS practice, what happened with QTiles for QGIS 3.

@gamayos @alexbruy: Can you pls. make a pull request containing the code of "QTiles3"? GPL requires that the code is published under same license and accessible.

Following comments on QTiles3: 
- I'm unsure if you asked NextGis to rename QTiles to QTiles3? I personally would stick to QTiles. 
- In metadata.txt the 3 entries "homepage, tracker, repository" are all are pointing to the original repo https://github.com/nextgis/QTiles - which would be correct, if the code for QTiles3 would be there.

The latter point should IMHO have been checked by the plugin maintainers which. I'll write a mail also to the QGIS Developer Mailing List regarding this issue.

**Comment by kannes** [comment]
@gamayos please review @sfkeller's comment above. Where is the source? Where is the PR?

**Comment by saberraz** [comment]
For those of you interested in this functionality, we have just submitted a PR to QGIS 3. Once accepted, it will be a core processing algorithm with identical functionality to this plugin in QGIS 3.8:
https://github.com/qgis/QGIS/pull/9857

We plan to have it ported the processing algorithm as a plugin for QGIS 3.4 and 3.6.

**Comment by dncpax** [comment]
This is great news. On the other hand qtiles3 plugin disappeared from the repo... which is unfortunate while things are still in the works...

**Comment by saberraz** [comment]
> which is unfortunate while things are still in the works...
We plan to release the XYZ processing plugin for QGIS 3.4 and 3.6 in the coming weeks.

**Comment by saberraz** [comment]
The processing plugin for generating tiles in QGIS 3.6 and earlier is now available from here:
https://plugins.qgis.org/plugins/tiles_xyz/

My suggestion to the developers of QTiles is to put their efforts in enhancing the core plugin.

**Comment by BishopGIS** [comment]
@saberraz And what users of QTiles plugin of QGIS 2 and 3 (before your core adds) have todo? It's more logical to add check to QTiles plugin of core functionality is exists. As it was done in QuickMapServices plugin (which check if XYZ provider is available or not).   

<img width="517" alt="Снимок экрана 2019-05-02 в 23 55 02" src="https://user-images.githubusercontent.com/1708122/57106341-c65a1f00-6d35-11e9-9c03-0ddb1bc5142c.png">

My suggestion to the developers of tiles_xyz is to put their efforts to enhancing existing and popular plugin, and not duplicates the work.

**Comment by saberraz** [comment]
QGIS 2.x is EOLed. The latest LTR is 3.4. If you'd like to still support your customers/clients for an unsupported version of QGIS, it is your business decision. But IMO, there is no need to dilute the code with obsolete APIs.

You are free to port QTiles to QGIS 3 but, as I suggested your help to have better processing algorithms in core QGIS is highly appreciated. This will stop these kind of work-arounds you are suggesting and uncertainties from users' prospective in future (QGIS 4 migration).

**Comment by simgislab** [comment]
closed because it is an absolute mess

**Comment by simgislab** [comment]
QTiles for QGIS 3 is released
