### ISSUE TITLE
Creating MBTiles does not work

### ISSUE THREAD

**Issue by oellampe** [nextgis/QTiles#99]
When trying to create an mbtile output, it doesn`t run. Creating a Zip-File output goes through and gives a good result.

I am Using QGIS 3.4 on a Windows 8.1.

![grafik](https://user-images.githubusercontent.com/37806320/52397019-30a35080-2ab4-11e9-8ac0-9f1362377551.png)

**Comment by GustaveCoste** [comment]
I have exactly the same issue with QGIS 3.6.0 and Windows 10.

**Comment by anjumzenith** [comment]
Same issue on my end too with 3.4

**Comment by tastrax** [comment]
Yep - still fails in 3.4.5 and 3.6 unfortunately

**Comment by StephPeriquet** [comment]
Same here under MacOS Mojave and QGIS3.6. Clicking on run does nothing...

**Comment by rikipasqui** [comment]
Here Windows 7 Pro and Qgis Noosa 3.6.0. Cannot generate .nrgc or any zipped file whatsoever. Only the option for generating a folder works.

**Comment by tastrax** [comment]
I suspect we are all experiencing an issue with QTILES3 not QTiles but unfortunately that plugin refers to this repository (which is incorrect) - https://github.com/alexbruy is who needs to be contacted for issues with QTILES3 however there is also no repository there either. Seems like QTLIES3 is in some blackhole somewhere that no-one can access

**Comment by dncpax** [comment]
Quick hack that got it working for me.

Find and replace in file mbutils.py:

Find:
`, silent):`

Replace with:
```
, **kwargs):
    silent = kwargs.get('silent')
```

Don't know why parameter "silent" gives error... seems it was released mid-way developing.

Wish that people envolved would come to terms that this was just an ordinary misunderstanding between good folk and get it sorted.

Anyway, thanks to all envolved.

**Comment by StephPeriquet** [comment]
Wow thanks so much, it did solve the problem for me too!

**Comment by boisjo** [comment]
Hello,

Where is the file mbutils.py ?

Thank you

**Comment by boisjo** [comment]
OK, I have found it

**Comment by rikipasqui** [comment]
.. all of the parameters "silent" have to be changed?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by StephPeriquet** [comment]
Yup, I did change all the occurrences of ", silent):"

**Comment by rikipasqui** [comment]
Thank you all so much for your great help. Looks like I'm a total newbie to the Python environment though, I cannot get it to work. Can any patient soul tell me step by step how to replace the lines without upsetting the code?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by tastrax** [comment]
If this is in connection with QTILES3 you should contact Alexander Bruy, although I have tried multiple times in order to get some support. He needs to change the meta details on his plugin as it should not point to NextGIS

 

https://github.com/alexbruy

https://wiki.osgeo.org/wiki/User:Alexbruy

alexander.bruy@gmail.com 

 

If anyone else knows how to report this error to those that run the plugin repository please send the details so both these developers can just get on with their individual projects.

 

I am like many others that would just like theQTILES3  plugin fixed without bugging NextGIS

 

Cheers - Phil

**Comment by rikipasqui** [comment]
Tried to replace the parts of that file, I get to open Qgis but Qtiles remains silent.. Same as before.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by boisjo** [comment]
Hello,
I have changed all the " , silent):" and nothing ;-(
Situation : "Run" stay ON, and 0%
A very small file is created !?
When I try to open this file with MapTiler, error message "myfile is malformated, missing tiles table" !
For information, I had no problem with Qtile/QGIS2.8 (just a little problem with QGis about the rotation of my "Etiquettes" (sorry I'm french).
Thank you

**Comment by dncpax** [comment]
QGIS shows errors from python plugins in the messages windows. You can open this by clicking in the bottom most right icon (a dialog bubble).
Here you can see various tabs, including python errors, and python messages.
That's where you get clues on what's failing.
Usually an unfinished plugin will dump messages here. And having the gui become unresponsive is a signal that some error occurred. You should look at this window to see if you can understand what's happening.

To be clear the replace of text makes the following effect:

Original lines:
`def mbtiles_connect(mbtiles_file, silent):`

After replace:
```
def mbtiles_connect(mbtiles_file, **kwargs):
    silent = kwargs.get('silent')
```

I hope this helps users get around their problems...

**Comment by jftence** [comment]
@dncpax 
Thanks a lot. I replaced all occurencies of  ", silent): in mbutils.py and that solved the issue.
(iMac running MacOS High Sierra). 
JeF

**Comment by Landast2020** [comment]
> 
> 
> When trying to create an mbtile output, it doesn`t run. Creating a Zip-File output goes through and gives a good result.
> 
> I am Using QGIS 3.4 on a Windows 8.1.
> 
> ![grafik](https://user-images.githubusercontent.com/37806320/52397019-30a35080-2ab4-11e9-8ac0-9f1362377551.png)

Hi
where can I find this plugin?
my Qgis vresion is 3.4 and 3.6

**Comment by Landast2020** [comment]
> 
> 
> @dncpax
> Thanks a lot. I replaced all occurencies of ", silent): in mbutils.py and that solved the issue.
> (iMac running MacOS High Sierra).
> JeF

Hi
where can I find this plugin?
my Qgis vresion is 3.4 and 3.6
![52397019-30a35080-2ab4-11e9-8ac0-9f1362377551](https://user-images.githubusercontent.com/50623041/57696286-44a3a480-7605-11e9-96ec-82f14ef7748c.png)

**Comment by jftence** [comment]
@Landast2020 
You get it from the QGIS plugin database (Plugins drop down menu). Go to settings and tick the box named "Show also experimental plugins". Then click "All" and type "QTiles3" in the search bar.
Once installed, don't forget to replace all occurrences of ", silent)" in file mbutils.py as specified by dncpax to enable MBTiles compression.  That's it.

**Comment by dncpax** [comment]
Hi everyone. Just to let you know that the qgis team has incorporated this functionality into qgis 3.6 and made a new plugin for version 3.4 - it is called tiles xyz: 
[https://plugins.qgis.org/plugins/tiles_xyz/](https://plugins.qgis.org/plugins/tiles_xyz/)

So try it out. It should work with no problems or at least less problems ;)

**Comment by Landast2020** [comment]
> 
> 
> Hi everyone. Just to let you know that the qgis team has incorporated this functionality into qgis 3.6 and made a new plugin for version 3.4 - it is called tiles xyz:
> https://plugins.qgis.org/plugins/tiles_xyz/
> 
> So try it out. It should work with no problems or at least less problems ;)

Excuse me.
I Couldn't load plugin 'tiles_xyz' and QGIS3.4 show bottom Error.
What is this Error??
![Capture](https://user-images.githubusercontent.com/50623041/57759701-580b4a00-76af-11e9-8171-46824f4c78e9.PNG)

**Comment by Landast2020** [comment]
> 
> 
> Hi everyone. Just to let you know that the qgis team has incorporated this functionality into qgis 3.6 and made a new plugin for version 3.4 - it is called tiles xyz:
> https://plugins.qgis.org/plugins/tiles_xyz/
> 
> So try it out. It should work with no problems or at least less problems ;)

Excuse me.
I Couldn't load plugin 'tiles_xyz' and QGIS3.4 show bottom Error.
What is this Error??
![Capture](https://user-images.githubusercontent.com/50623041/57759980-a6204d80-76af-11e9-9279-b187eaa577ef.PNG)

**Comment by Landast2020** [comment]
> QTiles3

I do your steps,But I dont find "QTiles3" in the search bar.why?
![q](https://user-images.githubusercontent.com/50623041/57776975-a03d6300-76d5-11e9-80d9-8648c94ec3f4.PNG)

**Comment by dncpax** [comment]
@Landast2020 please update qgis3.4.0 to latest 3.4.x. I just tried it yesterday and worked fine.

**Comment by boisjo** [comment]
Hello, 3.6.2 is also ok ☺️
JB

⁣Envoyé par TypeApp ​

Le 15 mai 2019 à 15:47, à 15:47, dncpax <notifications@github.com> a écrit:

**Comment by Landast2020** [comment]
> 
> 
> @Landast2020 please update qgis3.4.0 to latest 3.4.x. I just tried it yesterday and worked fine.

I installed version 3.4.8 and repeatedly searched for the QTILE3 plugin, but failed. Why do not you find it?

**Comment by tomptaylor** [comment]
I also could not find that QTILE3 in 3.4.  I saw a post saying mbtiles could be created 3.8 or >, but I only get to 1%, and the process becomes none responsive.
